// myYoutubePlayer/frontend/src/Components/Layout/Menu/Menu.tsx
import { useState } from "react";
import "./Menu.css";
import { NavLink } from "react-router-dom";

function Menu(): JSX.Element {
  const [categories, setCategories] = useState([]);

  return (
    <div className="Menu">
      <h2>Main Menu</h2>
      <hr />
      <NavLink to="/">All Songs</NavLink>
      <br />
      <br />
      <NavLink to="/addSong">Add Song</NavLink>
      <br />
      <br />
      <NavLink to="/addCategory">Add Category</NavLink>
      <br />
      <br />
      <NavLink to="/search">Search Song</NavLink>
      <br />
      <br />
      <NavLink to="/favorites">Favorites</NavLink>
      <br />
      <br />
      <NavLink to="/about">About Us</NavLink>
      <hr />
      {categories.map((category) => {
        return <h3>{category}</h3>;
      })}
    </div>
  );
}

export default Menu;

// Angular/youtube/src/app/Layout/menu/menu.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css'],
})
export class MenuComponent {
  constructor(private router: Router) {}

  nadavClick() {
    // console.log('Nadav the....');
    // Option 1 for using navigation:
    // this.router.navigate(['/player/U6XcNpYQ_zI']);
    // Option 2 for using navigation:
    this.router.navigate(['/player', 'U6XcNpYQ_zI']);
  }
}

<h2>Main Menu</h2>
<hr />
<h3>
  <a
    routerLink="/"
    [routerLinkActive]="['active']"
    [routerLinkActiveOptions]="{ exact: true }"
    >Home</a
  >
  <br /><br />
  <a routerLink="/list" [routerLinkActive]="['active']">All Songs</a>
  <br /><br />
  <a routerLink="/addSong" [routerLinkActive]="['active']">Add Song</a>
  <br /><br />
  <a routerLink="/addCategory" [routerLinkActive]="['active']">Add Category</a>
  <br /><br />
  <a routerLink="/categories" [routerLinkActive]="['active']">All Categories</a>
  <br /><br />
  <a routerLink="/about" [routerLinkActive]="['active']">About</a>
  <br /><br />
  <button (click)="nadavClick()">Go to Nadav Go!</button>
</h3>
